# main.yml - Activate EPEL
---
#- name: Instell Latest EPEL 7 Release
#  shell:  yum install "{{ epel_url }}" -y --nogpgcheck
# yum:
#   name: "{{ epel_url }}"
#   state: present
#   disable_gpg_check: yes
# tags:
#   - chromeRH7

# Make sure following RHEL Repos Enabled
# subscription-manager repos --enable rhel-7-server-extras-rpms
# subscription-manager repos --enable rhel-7-server-optional-rpms

- name: Install chrome
  yum:
    name: google-chrome
    state: present
    disable_gpg_check: yes

